const Uc07 = require('../models/Uc07');
const Funcionario = require('../models/Funcionario');
module.exports = {

    async index(req,res){
        const uc07 = await Uc07.findAll();

        return res.json(uc07);
            
    },
    async show(req, res){
        const { id }  = req.params;

        const uc07 = await Uc07.findByPk(id);

        return res.json(uc07);
    },

    async showData(req,res){
        const { data } = req.params;

        const where = {
            data : data
        };

        const uc07 = await Uc07.findAll({
            where
        });
    
        return res.json(uc07);   
    },



    async store(req,res){
        const { 
            nomeEquipamento,
            motorista,
            data,
            horaInicial,
            horaFinal,
            horimetroInicial,
            horimetroFinal,
            paradaInicial1,
            paradaFinal1,
            descricao1,
            paradaInicial2,
            paradaFinal2,
            descricao2,
            paradaInicial3,
            paradaFinal3,
            descricao3,
            paradaInicial4,
            paradaFinal4,
            descricao4,
            paradaInicial5,
            paradaFinal5,
            descricao5,
            paradaInicial6,
            paradaFinal6,
            descricao6,
            paradaInicial7,
            paradaFinal7,
            descricao7,
            paradaInicial8,
            paradaFinal8,
            descricao8,
            paradaInicial9,
            paradaFinal9,
            descricao9,
            paradaInicial10,
            paradaFinal10,
            descricao10,
            b0Vol,
            b0NumViagens,
            b0Mot,
            b1Vol,
            b1NumViagens,
            b1Mot,
            b2Vol,
            b2NumViagens,
            b2Mot,
            b4Vol,
            b4NumViagens,
            b4Mot,
            aimVol,
            aimNumViagens,
            aimMot,
            aifVol,
            aifNumViagens,
            aifMot,
            bicaVol,
            bicaNumViagens,
            bicaMot,
            amprToco,
            amprTruck,
            amprCarreta,
            amprAxor,
            amprObs,
            amumToco,
            amumTruck,
            amumCarreta,
            amumAxor,
            amumObs,
            afToco,
            afTruck,
            afCarreta,
            afAxor,
            afObs,
            pedToco,
            pedTruck,
            pedCarreta,
            pedAxor,
            pedObs,
            bicaPrToco,
            bicaPrTruck,
            bicaPrCarreta,
            bicaPrAxor,
            bicaPrObs,
            bica790Toco,
            bica790Truck,
            bica790Carreta,
            bica790Axor,
            bica790Obs,
            bicaUmToco,
            bicaUmTruck,
            bicaUmCarreta,
            bicaUmAxor,
            bicaUmObs,
            br1PrToco,
            br1PrTruck,
            br1PrCarreta,
            br1PrAxor,
            br1PrObs,
            br119Toco,
            br119Truck,
            br119Carreta,
            br119Axor,
            br119Obs,
            br0PrToco,
            br0PrTruck,
            br0PrCarreta,
            br0PrAxor,
            br0PrObs,
            br0UmToco,
            br0UmTruck,
            br0UmCarreta,
            br0UmAxor,
            br0UmObs,
            somaToco,
            somaTruck,
            somaCarreta,
            somaAxor,
            obsSoma,
            lanternagem,
            pneus,
            h2o,
            oleo,
            direcao,
            freios,
            parteEletrica,
            observacoes,
        } = req.body;

        const uc07 = await Uc07.create({
            nomeEquipamento,
            motorista,
            data,
            horaInicial,
            horaFinal,
            horimetroInicial,
            horimetroFinal,
            paradaInicial1,
            paradaFinal1,
            descricao1,
            paradaInicial2,
            paradaFinal2,
            descricao2,
            paradaInicial3,
            paradaFinal3,
            descricao3,
            paradaInicial4,
            paradaFinal4,
            descricao4,
            paradaInicial5,
            paradaFinal5,
            descricao5,
            paradaInicial6,
            paradaFinal6,
            descricao6,
            paradaInicial7,
            paradaFinal7,
            descricao7,
            paradaInicial8,
            paradaFinal8,
            descricao8,
            paradaInicial9,
            paradaFinal9,
            descricao9,
            paradaInicial10,
            paradaFinal10,
            descricao10,
            b0Vol,
            b0NumViagens,
            b0Mot,
            b1Vol,
            b1NumViagens,
            b1Mot,
            b2Vol,
            b2NumViagens,
            b2Mot,
            b4Vol,
            b4NumViagens,
            b4Mot,
            aimVol,
            aimNumViagens,
            aimMot,
            aifVol,
            aifNumViagens,
            aifMot,
            bicaVol,
            bicaNumViagens,
            bicaMot,
            amprToco,
            amprTruck,
            amprCarreta,
            amprAxor,
            amprObs,
            amumToco,
            amumTruck,
            amumCarreta,
            amumAxor,
            amumObs,
            afToco,
            afTruck,
            afCarreta,
            afAxor,
            afObs,
            pedToco,
            pedTruck,
            pedCarreta,
            pedAxor,
            pedObs,
            bicaPrToco,
            bicaPrTruck,
            bicaPrCarreta,
            bicaPrAxor,
            bicaPrObs,
            bica790Toco,
            bica790Truck,
            bica790Carreta,
            bica790Axor,
            bica790Obs,
            bicaUmToco,
            bicaUmTruck,
            bicaUmCarreta,
            bicaUmAxor,
            bicaUmObs,
            br1PrToco,
            br1PrTruck,
            br1PrCarreta,
            br1PrAxor,
            br1PrObs,
            br119Toco,
            br119Truck,
            br119Carreta,
            br119Axor,
            br119Obs,
            br0PrToco,
            br0PrTruck,
            br0PrCarreta,
            br0PrAxor,
            br0PrObs,
            br0UmToco,
            br0UmTruck,
            br0UmCarreta,
            br0UmAxor,
            br0UmObs,
            somaToco,
            somaTruck,
            somaCarreta,
            somaAxor,
            obsSoma,
            lanternagem,
            pneus,
            h2o,
            oleo,
            direcao,
            freios,
            parteEletrica,
            observacoes,
        });

        return res.json(uc07);
    }
}