const { Model, DataTypes } = require('sequelize');

class Usina extends Model {
    static init(sequelize) {
        super.init({
            nomeEquipamento:DataTypes.STRING,
            motorista: DataTypes.STRING,
            data: DataTypes.STRING,
            horaInicial: DataTypes.STRING,
            horaFinal: DataTypes.STRING,
            horimetroInicial: DataTypes.STRING,
            horimetroFinal: DataTypes.STRING,
            paradaInicial1: DataTypes.STRING,
            paradaFinal1: DataTypes.STRING,
            descricao1: DataTypes.STRING,
            paradaInicial2: DataTypes.STRING,
            paradaFinal2: DataTypes.STRING,
            descricao2: DataTypes.STRING,
            paradaInicial3: DataTypes.STRING,
            paradaFinal3: DataTypes.STRING,
            descricao3: DataTypes.STRING,
            paradaInicial4: DataTypes.STRING,
            paradaFinal4: DataTypes.STRING,
            descricao4: DataTypes.STRING,
            paradaInicial5: DataTypes.STRING,
            paradaFinal5: DataTypes.STRING,
            descricao5: DataTypes.STRING,
            paradaInicial6: DataTypes.STRING,
            paradaFinal6: DataTypes.STRING,
            descricao6: DataTypes.STRING,
            paradaInicial7: DataTypes.STRING,
            paradaFinal7: DataTypes.STRING,
            descricao7: DataTypes.STRING,
            paradaInicial8: DataTypes.STRING,
            paradaFinal8: DataTypes.STRING,
            descricao8: DataTypes.STRING,
            paradaInicial9: DataTypes.STRING,
            paradaFinal9: DataTypes.STRING,
            descricao9: DataTypes.STRING,
            paradaInicial10: DataTypes.STRING,
            paradaFinal10: DataTypes.STRING,
            descricao10: DataTypes.STRING,
            mot1: DataTypes.STRING,
            tf1: DataTypes.STRING,
            am1: DataTypes.STRING,
            b01: DataTypes.STRING,
            b11: DataTypes.STRING,
            mot1Soma: DataTypes.STRING,
            mot2: DataTypes.STRING,
            tf2: DataTypes.STRING,
            am2: DataTypes.STRING,
            b02: DataTypes.STRING,
            b12: DataTypes.STRING,
            mot2Soma: DataTypes.STRING,
            mot3: DataTypes.STRING,
            tf3: DataTypes.STRING,
            am3: DataTypes.STRING,
            b03: DataTypes.STRING,
            b13: DataTypes.STRING,
            mot3Soma: DataTypes.STRING,
            mot4: DataTypes.STRING,
            tf4: DataTypes.STRING,
            am4: DataTypes.STRING,
            b04: DataTypes.STRING,
            b14: DataTypes.STRING,
            mot4Soma: DataTypes.STRING,
            mot5: DataTypes.STRING,
            tf5: DataTypes.STRING,
            am5: DataTypes.STRING,
            b05: DataTypes.STRING,
            b15: DataTypes.STRING,
            mot5Soma: DataTypes.STRING,
            mot6: DataTypes.STRING,
            tf6: DataTypes.STRING,
            am6: DataTypes.STRING,
            b06: DataTypes.STRING,
            b16: DataTypes.STRING,
            mot6Soma: DataTypes.STRING,
            bandeja: DataTypes.STRING,
            rolo: DataTypes.STRING,
            rolete: DataTypes.STRING,
            alinha: DataTypes.STRING,
            egaiolada: DataTypes.STRING,
            observacoes: DataTypes.STRING,


        }, {
            sequelize
        })
    }
}

module.exports = Usina;